title: Copypasta
description: farkinga's copypasta
baseurl: "/copypasta" # the subpath of your site, e.g. /blog
url: "https://farkinga.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: farkinga

include: ["_pages", "_root"]
exclude: ["docs", "Readme.md", "Todo.md", "Makefile", "vendor", "Gemfile", "Gemfile.lock", "LICENSE"]

# Build settings
gems:
  - jekyll-sitemap
